export const products = [
    {
        name: "Nike Phantom GT2",
        price: 27000,
        stock: 4,
        category:"Nike",
        img: "https://res.cloudinary.com/alanleonelfernandez/image/upload/v1637114399/01_zrmvnt.jpg",
    },
    {
        name: "Adidas Predator Freak+",
        price: 28000,
        stock: 6,
        category:"Adidas",
        img: "https://res.cloudinary.com/alanleonelfernandez/image/upload/v1637114399/02_tumcgo.jpg",
    },
    {
        name: "Adidas X Ghosted.1",
        price: 26000,
        stock: 7,
        category:"Adidas",
        img: "https://res.cloudinary.com/alanleonelfernandez/image/upload/v1637114399/03_s8iquo.jpg",
    },
    {
        name: "Puma Future Z 1.1",
        price: 24000,
        stock: 5,
        category:"Puma",
        img: "https://res.cloudinary.com/alanleonelfernandez/image/upload/v1637114399/04_i0te0w.jpg",
    },
    {
        name: "Nike Mercurial Superfly 8",
        price: 27000,
        stock: 8,
        category:"Nike",
        img: "https://res.cloudinary.com/alanleonelfernandez/image/upload/v1637170078/05_irq1hf.jpg",
    },
    {
        name: "Puma Ultra Rimac",
        price: 23000,
        stock: 2,
        category:"Puma",
        img: "https://res.cloudinary.com/alanleonelfernandez/image/upload/v1637170078/06_zpdktk.jpg",
    },
    {
        name: "Adidas COPA +20",
        price: 25000,
        stock: 6,
        category:"Adidas",
        img: "https://res.cloudinary.com/alanleonelfernandez/image/upload/v1638287610/14_lqpnvt.jpg",
    },
    {
        name: "Adidas F50",
        price: 25000,
        stock: 3,
        category:"Adidas",
        img: "https://res.cloudinary.com/alanleonelfernandez/image/upload/v1638287610/12_c7mbof.jpg",
    },
    {
        name: "Nike Mercurial Superfly 7",
        price: 27000,
        stock: 9,
        category:"Nike",
        img: "https://res.cloudinary.com/alanleonelfernandez/image/upload/v1638287610/09_ofhhn8.jpg",
    },
    {
        name: "Adidas Nemeziz+",
        price: 27000,
        stock: 6,
        category:"Adidas",
        img: "https://res.cloudinary.com/alanleonelfernandez/image/upload/v1638287610/11_lyjthb.jpg",
    },
    {
        name: "Nike Tiempo Legend",
        price: 26000,
        stock: 5,
        category:"Nike",
        img: "https://res.cloudinary.com/alanleonelfernandez/image/upload/v1638289112/08_dckmsu.jpg",
    },
    {
        name: "Nike Mercurial Vapor 8",
        price: 27000,
        stock: 7,
        category:"Nike",
        img: "https://res.cloudinary.com/alanleonelfernandez/image/upload/v1638287609/07_dth4q5.jpg",
    },
    {
        name: "Adidas Predator Mutator",
        price: 25000,
        stock: 4,
        category:"Adidas",
        img: "https://res.cloudinary.com/alanleonelfernandez/image/upload/v1638287609/13_ad9k8h.jpg",
    },
    {
        name: "Puma Ultra 1.2",
        price: 24000,
        stock: 6,
        category:"Puma",
        img: "https://res.cloudinary.com/alanleonelfernandez/image/upload/v1638289112/10_hcgvn9.jpg",
    }
];
